SELECT g.ACCTGRPCOD, g.ACCTGRPDES, g.GRPCOD, a.ACCTID,
  a.ACCTFMTTD, a.ACCTDESC,fs.FSCSYR,
  SUM(fs.AMOUNT) AS AMOUNT, fs.FSPERD,
  EOMONTH(CONCAT(FSCSYR,FSPERD COLLATE DATABASE_DEFAULT)+'01') AS DATE,
  CASE a.ACCTTYPE
    WHEN 'I' THEN 'Income Statement'
    WHEN 'B' THEN 'Balance Sheet'
    WHEN 'R' THEN 'Retained Earnings'
  END AS ACCTTYPE,
  CASE fs.CURNTYPE
    WHEN 'S' THEN 'Source'
    WHEN 'E' THEN 'Equivalent'
    WHEN 'F' THEN 'Functional'
  END AS CURNTYPE
FROM GLACGRP g
JOIN GLAMF a ON g.ACCTGRPCOD = a.ACCTGRPCOD
JOIN fiscal_sets fs ON a.ACCTID = fs.ACCTID
WHERE fs.FSCSDSG = 'A'
GROUP BY g.ACCTGRPCOD, g.ACCTGRPDES, g.GRPCOD, a.ACCTID,
  a.ACCTFMTTD, a.ACCTDESC, a.ACCTTYPE, fs.FSCSYR, fs.FSPERD,
  fs.CURNTYPE
