SELECT [ITEMNO], [FMTITEMNO], [DESC], [CATEGORY]
    ,[CDESC], [OPTFCAT], [OPTFDEP], [OPTFPROD]
    ,[OPTFTYPE], it.abc_sales_rank, it.dense_sales_rank
    ,SUM([QTYONHAND]) AS QTYONHAND
    ,SUM([QTYCOMMIT]) AS QTYCOMMIT
    ,SUM([QTYSALORDR]) AS QTYSALORDR
    ,SUM([QTYONORDER]) AS QTYONORDER
    ,SUM([PRODUCTION]) AS PRODUCTION
    ,SUM([TOWYEARSQTY]) AS TOWYEARSQTY
    ,ISNULL(CASE (SUM(FOURQUARTERQTY)+SUM(THIRDQUARTERQTY)+SUM(SECONDQUARTERQTY)+SUM(FIRSTQUARTERQTY))
    WHEN 0 THEN 0.00
      ELSE ((SUM(QTYONHAND) - SUM(QTYCOMMIT))/((SUM(FOURQUARTERQTY)+SUM(THIRDQUARTERQTY)+SUM(SECONDQUARTERQTY)+SUM(FIRSTQUARTERQTY))/4))
    END,0.0) AS COVERAGE
    ,SUM([FOURQUARTERQTY]) AS FOURQUARTERQTY
    ,SUM([THIRDQUARTERQTY]) AS THIRDQUARTERQTY
    ,SUM([SECONDQUARTERQTY]) AS SECONDQUARTERQTY
    ,SUM([FIRSTQUARTERQTY]) AS FIRSTQUARTERQTY
    ,SUM([TOWYEARSAMT]) AS TOWYEARSAMT
    ,SUM([FOURQUARTERAMT]) AS FOURQUARTERAMT
    ,SUM([THIRDQUARTERAMT]) AS THIRDQUARTERAMT
    ,SUM([SECONDQUARTERAMT]) AS SECONDQUARTERAMT
    ,SUM([FIRSTQUARTERAMT]) AS FIRSTQUARTERAMT
    ,SUM([TRANSFOUT]) AS TRANSFOUT
    ,SUM([TRANSFIN]) AS TRANSFIN
    ,VENDOR1, VENDOR2, VENDOR3, VENDOR4, VENDOR5, VENDOR6
FROM items_location_details cd
LEFT JOIN items_rankings it ON ITEMNO = it.item
GROUP BY [ITEMNO], [FMTITEMNO], [DESC] ,[CATEGORY],
    [CDESC], [OPTFCAT], [OPTFDEP], [OPTFDEP], [OPTFPROD],
    [OPTFTYPE], it.abc_sales_rank, it.dense_sales_rank,
    VENDOR1, VENDOR2, VENDOR3, VENDOR4, VENDOR5, VENDOR6
