SELECT 
  ITEMNO, FMTITEMNO, [DESC], CATEGORY, COMMODIM, STOCKUNIT,
  (
    SELECT LTRIM(RTRIM(VALUE))
    FROM dbo.ICITEMO AS o
    WHERE (i.ITEMNO = o.ITEMNO) AND (OPTFIELD = 'DUTY')
  ) AS DUTY,
  (
    SELECT LTRIM(RTRIM(VALUE))
    FROM dbo.ICITEMO AS o
    WHERE (i.ITEMNO = o.ITEMNO) AND (OPTFIELD = 'DUTY1')
  ) AS DUTY1,
  (
    SELECT LTRIM(RTRIM(VALUE))
    FROM dbo.ICITEMO AS o
    WHERE (i.ITEMNO = o.ITEMNO) AND (OPTFIELD = 'DUTY2')
  ) AS DUTY2,
  (
    SELECT LTRIM(RTRIM(VALUE))
    FROM dbo.ICITEMO AS o
    WHERE (i.ITEMNO = o.ITEMNO) AND (OPTFIELD = 'DUTY3')
  ) AS DUTY3		
FROM dbo.ICITEM i
