SELECT
    LTRIM(RTRIM(ph.VENDOR)) AS VENDOR,
    LTRIM(RTRIM(v.VENDNAME)) AS VENDNAME,
    LTRIM(RTRIM(v.CODECTRY)) AS COUNTRY,
    LTRIM(RTRIM(ph.ITEMNO)) AS ITEMNO,
    LTRIM(RTRIM(i.FMTITEMNO)) AS FMTITEMNO,
    LTRIM(RTRIM(i.[DESC])) AS ITEMDESC,
    LTRIM(RTRIM(i.CATEGORY)) AS CATEGORY,
    LTRIM(RTRIM(c.[DESC])) AS CATDESC,
    ph.FISCYEAR,
    ph.FISCPERIOD,
    
    -- Optional Fields --
    (
        SELECT LTRIM(RTRIM(VALUE))
        FROM ICITEMO AS o
        WHERE (ph.ITEMNO = o.ITEMNO) AND (OPTFIELD = 'CATEGORY')
    ) AS OPTFCAT,
    (
        SELECT LTRIM(RTRIM(VALUE))
        FROM ICITEMO AS o
        WHERE (ph.ITEMNO = ITEMNO) AND (OPTFIELD = 'PRODUCT')
    ) AS OPTFPROD,
    (
        SELECT LTRIM(RTRIM(VALUE))
        FROM ICITEMO AS o
        WHERE (ph.ITEMNO = ITEMNO) AND (OPTFIELD = 'TYPE')
    ) AS OPTFTYPE,
    (
        SELECT LTRIM(RTRIM(VALUE))
        FROM ICITEMO AS o
        WHERE (ph.ITEMNO = ITEMNO) AND (OPTFIELD = 'SUBFAMILY')
    ) AS SUBFAMILY,
    -- End Optinal Fields --

    SUM(ph.SQINVTOTAL) AS RQTOTAL,
    SUM(ph.SCINVTOTAL) AS SCTOTAL,
    SUM(ph.FCINVTOTAL) AS FCTOTAL,
    SUM(ph.FCINVTOTAL+ph.FCCRNTOTAL) AS NETPURCHASE,
    SUM(ph.FCCRNTOTAL) AS FCCRNTOTAL,
    SUM(ph.FCDEBTOTAL) AS SCDISCTOT

FROM POHSTH ph
    LEFT JOIN ICITEM i ON ph.ITEMNO = i.ITEMNO
    LEFT JOIN ICCATG c ON i.CATEGORY = c.CATEGORY
    JOIN APVEN v ON v.VENDORID = ph.VENDOR
WHERE (ph.FISCYEAR >= YEAR(DATEADD(MONTH, - 60, GETDATE())))
AND v.IDGRP = 'PRO'
GROUP BY
    ph.VENDOR,
    v.VENDNAME,
    v.CODECTRY,
    ph.ITEMNO,
    i.FMTITEMNO,
    i.[DESC],
    i.CATEGORY,
    c.[DESC],
    ph.FISCYEAR,
    ph.FISCPERIOD
