SELECT
  CUSTOMER, ITEM, YR, PERIOD, SALESPER, TERRITORY, CATEGORY, LOCATION,
  SUM(QTYSOLD) AS QTYSOLD, SUM(FAMTSALES) AS FAMTSALES, SUM(FCSTSALES) AS FCSTSALES,
  SUM(FRETSALES) AS FRETSALES, SUM(NETSALES) AS NETSALES, SUM(MARAMOUNT) AS MARAMOUNT,
  SUM(YTDQTYSOLD) AS YTDQTYSOLD, SUM(YTDFAMTSALES) AS YTDFAMSALES,
  SUM(YTDFCSTSALES) AS YTDFCSTSALES, SUM(YTDFRETSALES) AS YTDFRETSALES, 
  SUM(YTDNETSALES) AS YTDNETSALES, SUM(YTDGROSMARGIN) AS YTDGORSMARGIN
FROM sales_history_details
GROUP BY CUSTOMER, ITEM, YR, PERIOD, SALESPER, TERRITORY, CATEGORY, LOCATION
