# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f9e265fbcc29c4e820116fa9ec6e9c5dc4a4cec544e6a46871748a5fa456b4ec42c0fce4b79bf9b9fd5fe5c3a32ead495570f93263a5d5b6ab18e5cab60bd5
  google_places_key: <%= ENV["GOOGLE_PLACES"] %>
  access_key_id: <%= ENV["ERP_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["ERP_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: c3996c3558f35558d29a4d5620a352168d65ca6519b52b38b738e39f71b0faa593b9462e94ceeb71fe2d3506f9643a131ff8d6e2be607e1121270005ca726b97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  access_key_id: <%= ENV["ERP_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["ERP_SECRET_ACCESS_KEY"] %>
