class CreateViewOrdersToFulfill < ActiveRecord::Migration[5.1]
  def change
    execute <<-SQL
      drop view if exists OrdersToFulfill
    SQL

    execute <<-SQL
      CREATE VIEW OrdersToFulfill AS
      SELECT
        TOP (100) PERCENT dbo.OEORDD.ITEM, dbo.ICITEM.[DESC], dbo.OEORDH.ORDUNIQ, dbo.OEORDH.ORDNUMBER, dbo.OEORDD.LOCATION, 
        dbo.OEORDH.CUSTOMER, dbo.OEORDH.BILNAME AS CUSTNAME, dbo.OEORDH.SALESPER1 AS SALESREP, dbo.OEORDH.ORDDATE, dbo.OEORDD.QTYORDERED, 
        dbo.OEORDD.QTYBACKORD, dbo.OEORDD.QTYCOMMIT, dbo.ICILOC.QTYONHAND - dbo.ICILOC.QTYCOMMIT AS QTYAVAILABLE, 
        dbo.OEORDD.UNITPRICE * dbo.OEORDD.QTYBACKORD AS AMOUNT, dbo.OEORDH.CUSTGROUP
      FROM dbo.OEORDH 
      INNER JOIN dbo.OEORDD ON dbo.OEORDD.ORDUNIQ = dbo.OEORDH.ORDUNIQ
      INNER JOIN dbo.ICILOC ON REPLACE(dbo.OEORDD.ITEM, '-', '') = dbo.ICILOC.ITEMNO 
        AND dbo.OEORDD.QTYBACKORD < dbo.ICILOC.QTYONHAND - dbo.ICILOC.QTYCOMMIT 
        AND dbo.OEORDD.LOCATION = dbo.ICILOC.LOCATION 
      INNER JOIN dbo.ICITEM ON dbo.ICILOC.ITEMNO = dbo.ICITEM.ITEMNO
      WHERE     (dbo.OEORDH.TYPE <> 4) AND (dbo.OEORDD.QTYBACKORD - dbo.OEORDD.QTYCOMMIT > 0) AND (dbo.OEORDD.COMPLETE = 0)
      ORDER BY dbo.OEORDH.ORDDATE
    SQL
  end
end
