class CreateViewSalesHistorySummaryBase < ActiveRecord::Migration[5.1]
  def change
    execute <<-SQL
      drop view if exists SalesHistorySummaryBase
    SQL

    execute <<-SQL
      CREATE VIEW SalesHistorySummaryBase AS
      SELECT
        CUSTOMER, ITEM, YR, PERIOD, SALESPER, TERRITORY, CATEGORY, LOCATION,
        SUM(QTYSOLD) AS QTYSOLD, SUM(FAMTSALES) AS FAMTSALES, SUM(FCSTSALES) AS FCSTSALES,
        SUM(FRETSALES) AS FRETSALES, SUM(NETSALES) AS NETSALES, SUM(MARAMOUNT) AS MARAMOUNT,
        SUM(YTDQTYSOLD) AS YTDQTYSOLD, SUM(YTDFAMTSALES) AS YTDFAMSALES,
        SUM(YTDFCSTSALES) AS YTDFCSTSALES, SUM(YTDFRETSALES) AS YTDFRETSALES, 
        SUM(YTDNETSALES) AS YTDNETSALES, SUM(YTDGROSMARGIN) AS YTDGORSMARGIN
      FROM dbo.SalesHistoryDetail
      GROUP BY CUSTOMER, ITEM, YR, PERIOD, SALESPER, TERRITORY, CATEGORY, LOCATION
    SQL
  end
end
