class CreateViewCustomerRanking < ActiveRecord::Migration[5.1]
  def change
    execute <<-SQL
      drop view if exists CustomersRanking
    SQL

    execute <<-SQL
    CREATE VIEW [dbo].[CustomersRanking] AS
    SELECT
      q.CUSTOMER,
      CASE
        WHEN SUM(SALES_AMOUNT) OVER (ORDER BY SALES_AMOUNT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / NULLIF(SUM(SALES_AMOUNT) OVER (),0) <= 0.7 THEN 'A'
        WHEN SUM(SALES_AMOUNT) OVER (ORDER BY SALES_AMOUNT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / NULLIF(SUM(SALES_AMOUNT) OVER (),0) <= 0.9 THEN 'B'
        ELSE 'C'
      END AS ABC_SALES_RANK,
      DENSE_RANK() OVER (PARTITION BY 1,2 ORDER BY SALES_AMOUNT DESC) AS DENSE_SALES_RANK,

      CASE
        WHEN SUM(MARGIN_AMOUNT) OVER (ORDER BY MARGIN_AMOUNT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / NULLIF(SUM(MARGIN_AMOUNT) OVER (),0) <= 0.7 THEN 'A'
        WHEN SUM(MARGIN_AMOUNT) OVER (ORDER BY MARGIN_AMOUNT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / NULLIF(SUM(MARGIN_AMOUNT) OVER (),0) <= 0.9 THEN 'B'
        ELSE 'C'
      END AS ABC_MARGIN_RANK,
      DENSE_RANK() OVER (PARTITION BY 1,2 ORDER BY MARGIN_AMOUNT DESC) AS DENSE_MARGIN_RANK,
      CASE
        WHEN SUM(MARGIN_PERCENT) OVER (ORDER BY MARGIN_PERCENT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / NULLIF(SUM(MARGIN_PERCENT) OVER (),0) <= 0.7 THEN 'A'
        WHEN SUM(MARGIN_PERCENT) OVER (ORDER BY MARGIN_PERCENT DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / NULLIF(SUM(MARGIN_PERCENT) OVER (),0) <= 0.9 THEN 'B'
        ELSE 'C'
      END AS ABC_PERCENT_RANK,
      DENSE_RANK() OVER (PARTITION BY 1,2 ORDER BY MARGIN_PERCENT DESC) AS DENSE_PERCENT_RANK
      FROM
        (SELECT
          RTRIM(CUSTOMER) AS CUSTOMER,
          SUM(FAMTSALES)-SUM(FRETSALES) AS SALES_AMOUNT,
          SUM(FCSTSALES) AS COST_AMOUNT,
          SUM(FAMTSALES)-SUM(FRETSALES)-SUM(FCSTSALES) AS MARGIN_AMOUNT,
          CASE
            WHEN SUM(FAMTSALES) = 0 OR SUM(FCSTSALES) = 0
            THEN 0
          ELSE ((SUM(FAMTSALES)-SUM(FRETSALES)-SUM(FCSTSALES))/SUM(FAMTSALES)*100)
          END AS MARGIN_PERCENT
        FROM OESHDT
        WHERE DATEADD(MONTH, -36, GETDATE()) <= CONVERT(DATE,NULLIF(CONVERT(VARCHAR(10),CONVERT(INT,TRANDATE)),0))
        GROUP BY CUSTOMER) q 
    SQL
  end
end
